### PR TITLE
Add EulerA scheduler

### PR DESCRIPTION
**Pull request by jdluzen**
Currently ~is borken~ works thanks to Cassie.

### CODE REVIEW

**Comment by cassiebreviu** [comment]
Fixed LMS scheduler and pushed changes here. SetTimeSteps needed to be set in the scheduler because it uses the global sigmas values.

**Comment by cassiebreviu** [comment]
@jdluzen Can you share the model you are using?

**Comment by cassiebreviu** [comment]
@jdluzen I was able to fix the euler scheduler and get it working on my model. Can you test on your model and let me know if it works for you?

**Comment by jdluzen** [comment]
It works! UINT8 quantized too! Did I port the wrong file? I was using the original 1.5 fp32.

**Comment by cassiebreviu** [comment]
Yay!! I am going to refactor the scheduler a bit in a new PR to main because I am also working on an EP config in main rather than having branches for each EP. 

You didnt port the wrong file but there were issues in the math. Python and PyTorch handle some math operations and random generation differently than C# so it needs to be implemented different to work correctly.

Thanks!!

**Pull request closed without merging**
